### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by srmnitc**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
> @jan-janssen @pmrv could you please check?

Can you update the dependencies to be compatible with https://github.com/pyiron/pyiron_contrib/blob/master/.ci_support/environment.yml ?

**Comment by srmnitc** [comment]
> > @jan-janssen @pmrv could you please check?
> 
> Can you update the dependencies to be compatible with https://github.com/pyiron/pyiron_contrib/blob/master/.ci_support/environment.yml ?

done

**Comment by pmrv** [comment]
I don't think Yury opened one already.

**Comment by srmnitc** [comment]
@pmrv Once you give this a check and merge, we should be ready for the final update of the env

**Pull request merged**
